spigot:
  container_name: bitquest
  environment:
    - BITQUEST_ENV=development
  build: .
  volumes:
    - "./build/libs/:/spigot/plugins"
    - ".:/bitquest"
  ports:
    - "25565:25565"
  links:
    - redis
redis:
  image: redis
